### PR TITLE
awaitable send

### PR DESCRIPTION
**Pull request by amarzavery**
#45

### CODE REVIEW

**Comment by amarzavery** [comment]
@swilliams-a3digital - Do take a look at this PR. However, I am not sure if this library is the right place for this implementation.

- The method could have a retry logic, which I have not implemented here.
- Another problem is that event listeners will be added and removed for every send. node.js allows 11 listeners to be attached on an event emitter object by default. After that it emits memory leak warning. Although this limit can be increased by setting an environment variable.


A better implementation would be to add event listeners once and then maintain a map of Promises that can be resolved or rejected based on the event that was fired. In this way one does not hit the default event listener limit of 11 and things move faster.

**Comment by amarzavery** [comment]
closing in favor of #44.

**Comment by swilliams-a3digital** [comment]
I agree that one listener with a map of promises is probably necessary.

**Comment by amarzavery** [comment]
@swilliams-a3digital - Please take a look at the [AsynchronousSender](https://github.com/amqp/rhea-promise/pull/44/files#diff-dabb296f744cd7f74c64b7439f75660aR44) that implements the send operation using an internal map.

**Pull request closed without merging**
