### PR TITLE
use prepack instead of prepare in npm scripts

### PR DESCRIPTION
**Pull request by amarzavery**

### CODE REVIEW

**Comment by amarzavery** [comment]
@elbuo8 - Let me know if this works for you.

In your package.json inside "dependencies", try updating "rhea-promise" to "amarzavery/rhea-promise#event" and let me know if that works for you?

**Comment by amarzavery** [comment]
@elbuo8 - Tested it on my dev box and it worked as expected:

my package.json
```json5
"dependencies": {
    "rhea-promise": "amarzavery/rhea-promise#event"
}
```

```bash
Amars-MBP:tmp amarz$ npm i

> rhea-promise@0.1.9 prepack /Users/amarz/.npm/_cacache/tmp/git-clone-243774c5
> npm i && npm run build

added 59 packages from 90 contributors and audited 89 packages in 1.632s
found 0 vulnerabilities


> rhea-promise@0.1.9 prebuild /Users/amarz/.npm/_cacache/tmp/git-clone-243774c5
> rimraf dist && rimraf typings


> rhea-promise@0.1.9 build /Users/amarz/.npm/_cacache/tmp/git-clone-243774c5
> npm run tslint && npm run tsc


> rhea-promise@0.1.9 tslint /Users/amarz/.npm/_cacache/tmp/git-clone-243774c5
> tslint -p . -c tslint.json --exclude tests/**/*.ts


> rhea-promise@0.1.9 tsc /Users/amarz/.npm/_cacache/tmp/git-clone-243774c5
> tsc

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN tmp No description
npm WARN tmp No repository field.
npm WARN tmp No license field.

added 2 packages from 1 contributor and audited 8 packages in 8.15s
found 0 vulnerabilities

Amars-MBP:tmp amarz$ ls -al node_modules/rhea-promise
total 96
drwxr-xr-x  13 amarz  staff    416 Oct 24 14:05 .
drwxr-xr-x   8 amarz  staff    256 Oct 24 14:05 ..
-rw-r--r--   1 amarz  staff     74 Oct 26  1985 .travis.yml
-rw-r--r--   1 amarz  staff   3221 Oct 26  1985 CODE_OF_CONDUCT.md
-rw-r--r--   1 amarz  staff  11357 Oct 26  1985 LICENSE
-rw-r--r--   1 amarz  staff   9363 Oct 26  1985 README.md
-rw-r--r--   1 amarz  staff   1594 Oct 26  1985 changelog.md
drwxr-xr-x   3 amarz  staff     96 Oct 24 14:05 dist
drwxr-xr-x  13 amarz  staff    416 Oct 24 14:05 lib
-rw-r--r--   1 amarz  staff   1927 Oct 24 14:05 package.json
-rw-r--r--   1 amarz  staff    596 Oct 26  1985 tsconfig.json
-rw-r--r--   1 amarz  staff   2228 Oct 26  1985 tslint.json
drwxr-xr-x   3 amarz  staff     96 Oct 24 14:05 typings
```

**Comment by elbuo8** [comment]
@amarzavery `npm` works, `yarn` doesn't.

**Comment by elbuo8** [comment]
My bad, it does work. 💯

**Comment by amarzavery** [comment]
Awesome. Will merge this PR and publish 0.1.9. Thanks for taking the time to make this a better product.

**Comment by amarzavery** [comment]
@elbuo8 - 0.1.9 has been published to npm.

**Pull request merged**
